In [ ]:
## 2x3 integer array containing sequential values from 7 to 12

import numpy as np
m = np.array([[7,8,9],[10,11,12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
### 1D array of 15 even integers from 0 to 28

n = np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
## Reshaped the 15 elements into a 3x5 2D array (3 rows, 5 columns)

n = n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [3]:
#ones returns a new array of given shape and type, filled with ones

np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
#zeroes returns a new array of given shape and type filled with zeroes

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
#matrix creation by array input

num= np.matrix([[11,121,130],
[613,34,13],
[514,50,16]])
num

matrix([[ 11, 121, 130],
        [613,  34,  13],
        [514,  50,  16]])

In [10]:
type(num)

numpy.matrix

In [11]:
print("main diagonal elements:\n", np.diag(num))
print("\nDiagonal elements above main diagonal:\n", np.diag(num,1))
print("\nDiagonal elements below main diagonal:\n", np.diag(num,-1))

main diagonal elements:
 [11 34 16]

Diagonal elements above main diagonal:
 [121  13]

Diagonal elements below main diagonal:
 [613  50]


In [ ]:
#create an array using repeating list

np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [13]:
#repeat elements of an array using repeat

np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [17]:
#combining arrays

p=np.ones([3,3], int)
p

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
#use vstack to stack arrays in sequence vertically

np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [20]:
#use hstack to stack arrays in sequence horizontally

np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [21]:
np.hstack([p, 2*p, 3*p])

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [1, 1, 1, 2, 2, 2, 3, 3, 3],
       [1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [22]:
#operations
#use +,-,*,/ and ** to perform element wise addition, sub, multi, division
x= np.array([1,2,3])
y= np.array([4,5,6])
print(x)
print(y)

[1 2 3]
[4 5 6]


In [24]:
print(x+y) #elementwise addition
print(x-y) #elementwise subtration
print(x*y) #elementwise multiplication
print(x/y) #elementwise division
print(x**y) #elementwise power
print(x@y) #dot product

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]
32


In [25]:
x.dot(y) #dot product

np.int64(32)

In [ ]:
#myexample
a= np.array([10,20,30])
b= np.array([40,50,60])
print(a)
print(b)

[10 20 30]
[40 50 60]


In [27]:
print(a+b) #elementwise addition
print(a-b) #elementwise subtration
print(a*b) #elementwise multiplication
print(a/b) #elementwise division
print(a*b) #elementwise power
print(a@b) #dot product

[50 70 90]
[-30 -30 -30]
[ 400 1000 1800]
[0.25 0.4  0.5 ]
[ 400 1000 1800]
3200


In [30]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [31]:
print(len(z)) #no.of rows of array

2


In [32]:
#shape of array z is (2,3) before transposing
z.shape

(2, 3)

In [34]:
z.T #fetches the transpose

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [33]:
z.T.shape

(3, 2)

In [35]:
z.dtype

dtype('int64')

In [36]:
z = z.astype('f') #typecasting to specified type
z.dtype

dtype('float32')

In [37]:
#math functions
#numpy has many built in math functions that can be performed on arrays

a= np.array([-4,-2,1,3,5])
a.sum()

np.int64(3)

In [38]:
a.max()

np.int64(5)

In [39]:
a.min()

np.int64(-4)

In [40]:
a.mean()

np.float64(0.6)

In [41]:
a.std()

np.float64(3.2619012860600183)

In [ ]:
#argmax and argmin return the index of the maximum and minimum values in the array
a.argmax()

np.int64(4)

In [43]:
a.argmin()

np.int64(0)

In [46]:
#myexample
a= np.array([7,3,-2,0,100,25])
a.sum()


np.int64(133)

In [47]:
a.max()

np.int64(100)

In [48]:
a.min()

np.int64(-2)

In [49]:
a.mean()

np.float64(22.166666666666668)

In [50]:
a.std()

np.float64(35.91386299962113)

In [51]:
a.argmax()

np.int64(4)

In [52]:
a.argmin()

np.int64(2)

In [53]:
#indexing/slicing
import numpy as np
s= np.arange(100)
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [55]:
s = np.arange(6)**2
s

array([ 0,  1,  4,  9, 16, 25])

In [56]:
#use bracket notation to get the value at a specific index
s[0], s[4], s[-1]

(np.int64(0), np.int64(16), np.int64(25))

In [57]:
#use : to indicate a range. array[start:stop]
s[1:5]

array([ 1,  4,  9, 16])

In [58]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [59]:
s[0], s[4], s[-1]

(np.int64(0), np.int64(16), np.int64(144))

In [60]:
#use negatives to count from back
s[-4:]

array([ 81, 100, 121, 144])

In [61]:
#starting 5th element from the end and count backwards with step of 2
s[-5::-2]

array([64, 36, 16,  4,  0])

In [62]:
s[-5:-2]

array([ 64,  81, 100])

In [64]:
#multidimensional array
r= np.arange(100)
r.resize((10,10))
r

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [66]:
#use bracket notation to slice: array[row, col]
r[3,4]

np.int64(34)

In [67]:
r[2, 1:4]

array([21, 22, 23])

In [68]:
r[3, 3:6]

array([33, 34, 35])

In [69]:
r[:3, :-1]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [20, 21, 22, 23, 24, 25, 26, 27, 28]])