1. Create a constant array
	Prints "[[ 7.  7.]
            [ 7.  7.]]"

In [2]:
import numpy as np

c = np.ones((2, 2)) * 7
c

array([[7., 7.],
       [7., 7.]])

2. Create an array filled with random values
Might print "[[ 0.91940167  0.08143941]
             [ 0.68744134  0.87236687]]"

In [ ]:
# Create an array filled with random values (between 0.0 and 1.0)
e= np.random.random((2,2))
print(e)

[[0.98228466 0.77358686]
 [0.7159969  0.27236266]]


3. Create a NumPy array containing the numbers from 10 to 50. Display:
The array
Number of elements
Shape
Dimension
Data type

In [ ]:
# Create array from 10 to 50
a= np.arange(10,51)
print("array: ",a)
print("no.of elements: ", a.size)
print("shape of array: ", a.shape)
print("dimension of array: ", a.ndim)
print("datatype of array: ", a.dtype)

array:  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
no.of elements:  41
shape of array:  (41,)
dimension of array:  1
datatype of array:  int64


4. Using NumPy, create:

A 1D array containing 10 zeros
A 3 × 3 array containing ones
A 4 × 4 identity matrix
An array containing numbers from 5 to 50 with a step size of 5.

In [ ]:
#1D array containing 10 zeros
zeros= np.zeros(10)
#3 × 3 array containing ones
ones= np.ones((3,3))
#4 × 4 identity matrix
identity= np.eye(4)
#array containing numbers from 5 to 50 with step=5
step_arr= np.arange(5,51,5)

print("1D array of 10 zeroes: \n", zeros)
print("3x3 array containing ones: \n", ones)
print("4x4 identity matrix: \n", identity)
print("array from 5 to 50: \n", step_arr)

1D array of 10 zeroes: 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
3x3 array containing ones: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
4x4 identity matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
array from 5 to 50: 
 [ 5 10 15 20 25 30 35 40 45 50]


5. Create an array containing numbers from 1 to 24. Reshape it into:
4 × 6
6 × 4
2 × 3 × 4
Display the shape and ndim of each result.

In [11]:
arr = np.arange(1,25)
#4 × 6
arr1 = arr.reshape(4,6)
print("shape:", arr1.shape, "|ndim:", arr1.ndim)
print(arr1)
#6 x 4
arr2 = arr.reshape(6,4)
print("shape:", arr2.shape, "|ndim:", arr2.ndim)
print(arr2)
#2 × 3 × 4
arr3 = arr.reshape(2,3,4)
print("shape:", arr3.shape, "|ndim:", arr3.ndim)
print(arr3)

shape: (4, 6) |ndim: 2
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
shape: (6, 4) |ndim: 2
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
shape: (2, 3, 4) |ndim: 3
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]



6. Consider: marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])

Write NumPy statements to display:
First element
Last element
Third element
First four elements
Last three elements

In [14]:
marks = np.array([78,85,92,67,88,73,95,81])
#First element
print("first element = ", marks[0])
#Last element
print("last element = ", marks[-1])
#third element
print("third element = ", marks[2])
#first 4 elements
print("first 4 = ", marks[:4])
#last 3 elements
print("last 3 = ", marks[-3:])

first element =  78
last element =  81
third element =  92
first 4 =  [78 85 92 67]
last 3 =  [73 95 81]


7. Create:
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])

Calculate:
a + b
a - b
a * b
a / b
Square of every element in a

In [16]:
a = np.array([10,20,30,40,50])
b = np.array([5,10,15,20,25])
#calculating sum, diff, product, quotient, squares
print("a+b = ", a+b)
print("a-b = ", a-b)
print("a*b = ", a*b)
print("a/b = ", a/b)
print("squares of a elements= ", a**2)

a+b =  [15 30 45 60 75]
a-b =  [ 5 10 15 20 25]
a*b =  [  50  200  450  800 1250]
a/b =  [2. 2. 2. 2. 2.]
squares of a elements=  [ 100  400  900 1600 2500]



8. Given:
salary = np.array([25000, 32000, 28000, 45000,
                   50000, 38000, 42000, 30000])

Find:
Total salary
Average salary
Highest salary
Lowest salary
Median salary
Standard deviation

In [17]:
salary = np.array([25000, 32000, 28000, 45000, 50000, 38000, 42000, 30000])

print("total salary = ", np.sum(salary))
print("avg salary = ", np.mean(salary))
print("highest salary = ", np.max(salary))
print("lowest salary = ", np.min(salary))
print("median salary = ", np.median(salary))
print("std.dev of salary = ", np.std(salary))

total salary =  290000
avg salary =  36250.0
highest salary =  50000
lowest salary =  25000
median salary =  35000.0
std.dev of salary =  8317.902379807063


11. Create:

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

Perform:

Matrix addition
Element-wise multiplication
Matrix multiplication
Transpose of A.

explain the difference between:
A * B and A @ B

In [18]:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

# Operations
add_res = A + B
elem_mult = A * B
matmul_res = A @ B  # or np.dot(A, B)
trans_A = A.T

print("Matrix Addition (A + B):\n", add_res)
print("\nElement-wise Multiplication (A * B):\n", elem_mult)
print("\nMatrix Multiplication (A @ B):\n", matmul_res)
print("\nTranspose of A (A.T):\n", trans_A)

Matrix Addition (A + B):
 [[ 6  8]
 [10 12]]

Element-wise Multiplication (A * B):
 [[ 5 12]
 [21 32]]

Matrix Multiplication (A @ B):
 [[19 22]
 [43 50]]

Transpose of A (A.T):
 [[1 3]
 [2 4]]
