1. Create a constant array
	Prints "[[ 7.  7.]
            [ 7.  7.]]"

In [2]:
import numpy as np

c = np.ones((2, 2)) * 7
c

array([[7., 7.],
       [7., 7.]])

2. Create an array filled with random values
Might print "[[ 0.91940167  0.08143941]
             [ 0.68744134  0.87236687]]"

In [ ]:
# Create an array filled with random values (between 0.0 and 1.0)
e= np.random.random((2,2))
print(e)

[[0.98228466 0.77358686]
 [0.7159969  0.27236266]]


3. Create a NumPy array containing the numbers from 10 to 50. Display:
The array
Number of elements
Shape
Dimension
Data type

In [ ]:
# Create array from 10 to 50
a= np.arange(10,51)
print("array: ",a)
print("no.of elements: ", a.size)
print("shape of array: ", a.shape)
print("dimension of array: ", a.ndim)
print("datatype of array: ", a.dtype)

array:  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
no.of elements:  41
shape of array:  (41,)
dimension of array:  1
datatype of array:  int64


4. Using NumPy, create:

A 1D array containing 10 zeros
A 3 × 3 array containing ones
A 4 × 4 identity matrix
An array containing numbers from 5 to 50 with a step size of 5.

In [ ]:
#1D array containing 10 zeros
zeros= np.zeros(10)
#3 × 3 array containing ones
ones= np.ones((3,3))
#4 × 4 identity matrix
identity= np.eye(4)
#array containing numbers from 5 to 50 with step=5
step_arr= np.arange(5,51,5)

print("1D array of 10 zeroes: \n", zeros)
print("3x3 array containing ones: \n", ones)
print("4x4 identity matrix: \n", identity)
print("array from 5 to 50: \n", step_arr)

1D array of 10 zeroes: 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
3x3 array containing ones: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
4x4 identity matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
array from 5 to 50: 
 [ 5 10 15 20 25 30 35 40 45 50]


5. Create an array containing numbers from 1 to 24. Reshape it into:
4 × 6
6 × 4
2 × 3 × 4
Display the shape and ndim of each result.

In [11]:
arr = np.arange(1,25)
#4 × 6
arr1 = arr.reshape(4,6)
print("shape:", arr1.shape, "|ndim:", arr1.ndim)
print(arr1)
#6 x 4
arr2 = arr.reshape(6,4)
print("shape:", arr2.shape, "|ndim:", arr2.ndim)
print(arr2)
#2 × 3 × 4
arr3 = arr.reshape(2,3,4)
print("shape:", arr3.shape, "|ndim:", arr3.ndim)
print(arr3)

shape: (4, 6) |ndim: 2
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
shape: (6, 4) |ndim: 2
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
shape: (2, 3, 4) |ndim: 3
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]



6. Consider: marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])

Write NumPy statements to display:
First element
Last element
Third element
First four elements
Last three elements

In [14]:
marks = np.array([78,85,92,67,88,73,95,81])
#First element
print("first element = ", marks[0])
#Last element
print("last element = ", marks[-1])
#third element
print("third element = ", marks[2])
#first 4 elements
print("first 4 = ", marks[:4])
#last 3 elements
print("last 3 = ", marks[-3:])

first element =  78
last element =  81
third element =  92
first 4 =  [78 85 92 67]
last 3 =  [73 95 81]


7. Create:
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])

Calculate:
a + b
a - b
a * b
a / b
Square of every element in a

In [16]:
a = np.array([10,20,30,40,50])
b = np.array([5,10,15,20,25])
#calculating sum, diff, product, quotient, squares
print("a+b = ", a+b)
print("a-b = ", a-b)
print("a*b = ", a*b)
print("a/b = ", a/b)
print("squares of a elements= ", a**2)

a+b =  [15 30 45 60 75]
a-b =  [ 5 10 15 20 25]
a*b =  [  50  200  450  800 1250]
a/b =  [2. 2. 2. 2. 2.]
squares of a elements=  [ 100  400  900 1600 2500]



8. Given:
salary = np.array([25000, 32000, 28000, 45000,
                   50000, 38000, 42000, 30000])

Find:
Total salary
Average salary
Highest salary
Lowest salary
Median salary
Standard deviation

In [17]:
salary = np.array([25000, 32000, 28000, 45000, 50000, 38000, 42000, 30000])

print("total salary = ", np.sum(salary))
print("avg salary = ", np.mean(salary))
print("highest salary = ", np.max(salary))
print("lowest salary = ", np.min(salary))
print("median salary = ", np.median(salary))
print("std.dev of salary = ", np.std(salary))

total salary =  290000
avg salary =  36250.0
highest salary =  50000
lowest salary =  25000
median salary =  35000.0
std.dev of salary =  8317.902379807063


In [1]:
import numpy as np

marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])

# Marks greater than 75
print("Marks > 75:", marks[marks > 75])

# Marks between 50 and 80
print("Marks between 50 and 80:", marks[(marks >= 50) & (marks <= 80)])

# Number of students who scored below 50
print("Students below 50:", np.sum(marks < 50))

# Percentage of students who scored 60 or above
pct_60_plus = np.mean(marks >= 60) * 100
print(f"Percentage scoring 60 or above: {pct_60_plus}%")

Marks > 75: [78 89 90 76 84]
Marks between 50 and 80: [78 67 55 76]
Students below 50: 3
Percentage scoring 60 or above: 60.0%


In [2]:
marks = np.array([
    [80, 75, 90],
    [65, 70, 72],
    [88, 92, 85],
    [55, 60, 58]
])

# Total & average marks of each student (row-wise)
student_totals = np.sum(marks, axis=1)
student_averages = np.mean(marks, axis=1)
print("Total marks of each student:", student_totals)
print("Average marks of each student:", student_averages)

# Average & highest mark in each subject (column-wise)
subject_averages = np.mean(marks, axis=0)
subject_max = np.max(marks, axis=0)
print("Average marks in each subject:", subject_averages)
print("Highest mark in each subject:", subject_max)

# Student with highest total (1-based index)
highest_student = np.argmax(student_totals) + 1
print("Student with highest total: Student", highest_student)

Total marks of each student: [245 207 265 173]
Average marks of each student: [81.66666667 69.         88.33333333 57.66666667]
Average marks in each subject: [72.   74.25 76.25]
Highest mark in each subject: [88 92 90]
Student with highest total: Student 3


11. Create:

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

Perform:

Matrix addition
Element-wise multiplication
Matrix multiplication
Transpose of A.

explain the difference between:
A * B and A @ B

In [18]:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

# Operations
add_res = A + B
elem_mult = A * B
matmul_res = A @ B  # or np.dot(A, B)
trans_A = A.T

print("Matrix Addition (A + B):\n", add_res)
print("\nElement-wise Multiplication (A * B):\n", elem_mult)
print("\nMatrix Multiplication (A @ B):\n", matmul_res)
print("\nTranspose of A (A.T):\n", trans_A)

Matrix Addition (A + B):
 [[ 6  8]
 [10 12]]

Element-wise Multiplication (A * B):
 [[ 5 12]
 [21 32]]

Matrix Multiplication (A @ B):
 [[19 22]
 [43 50]]

Transpose of A (A.T):
 [[1 3]
 [2 4]]


In [3]:
temperature = np.array([
    31, 32, 33, 35, 36, 34, 32,
    30, 29, 31, 33, 35, 37, 36
])

avg_temp = np.mean(temperature)
print("Mean temperature:", avg_temp)
print("Max temp:", np.max(temperature), "| Min temp:", np.min(temperature))
print("Days above average temp:", np.sum(temperature > avg_temp))
print("Temperatures > 34°C:", temperature[temperature > 34])
print("Difference between max & min:", np.max(temperature) - np.min(temperature))
print("Standard deviation:", np.std(temperature))

Mean temperature: 33.142857142857146
Max temp: 37 | Min temp: 29
Days above average temp: 6
Temperatures > 34°C: [35 36 35 37 36]
Difference between max & min: 8
Standard deviation: 2.356060357495806


In [4]:
sales = np.array([
    12000, 15000, 17000, 14000,
    18000, 21000, 19000, 22000,
    25000, 23000, 26000, 28000
])

print("Total annual sales:", np.sum(sales))
print("Average monthly sales:", np.mean(sales))
print("Month with highest sales: Month", np.argmax(sales) + 1)
print("Month with lowest sales: Month", np.argmin(sales) + 1)
print("Months with sales > ₹20,000:", np.sum(sales > 20000))

# Percentage increase from Jan (index 0) to Dec (index -1)
pct_increase = ((sales[-1] - sales[0]) / sales[0]) * 100
print(f"Percentage increase from Jan to Dec: {pct_increase:.2f}%")

Total annual sales: 240000
Average monthly sales: 20000.0
Month with highest sales: Month 12
Month with lowest sales: Month 1
Months with sales > ₹20,000: 6
Percentage increase from Jan to Dec: 133.33%


In [6]:
import numpy as np

marks = np.array([
    [78, 85, 90, 88],
    [65, 70, 72, 68],
    [92, 88, 95, 91],
    [55, 60, 58, 62],
    [80, 75, 82, 79]
])

student_totals = np.sum(marks, axis=1)
student_averages = np.mean(marks, axis=1)
subject_averages = np.mean(marks, axis=0)

print("Total marks of every student:", student_totals)
print("Average of every student:", student_averages)
print("Average mark for every subject:", subject_averages)
print("Highest-scoring student: Student", np.argmax(student_totals) + 1)
print("Lowest-scoring student: Student", np.argmin(student_totals) + 1)
print("Students with avg > 80: Students", np.where(student_averages > 80)[0] + 1)
print("Overall class average:", np.mean(marks))

# Categorize performance using np.select with explicit string default
conditions = [
    student_averages >= 85,
    (student_averages >= 70) & (student_averages < 85),
    (student_averages >= 50) & (student_averages < 70),
    student_averages < 50
]
categories = ['Excellent', 'Good', 'Average', 'Needs Improvement']

# Pass default='' to match string dtype
performance = np.select(conditions, categories, default='')

for i, cat in enumerate(performance):
    print(f"Student {i+1}: {cat}")

Total marks of every student: [341 275 366 235 316]
Average of every student: [85.25 68.75 91.5  58.75 79.  ]
Average mark for every subject: [74.  75.6 79.4 77.6]
Highest-scoring student: Student 3
Lowest-scoring student: Student 4
Students with avg > 80: Students [1 3]
Overall class average: 76.65
Student 1: Excellent
Student 2: Average
Student 3: Excellent
Student 4: Average
Student 5: Good


In [7]:
# Q15: Generate 20 random integers between 1 and 100
np.random.seed(42)  # For reproducibility
rand_arr = np.random.randint(1, 101, size=20)
print("15. Generated array:", rand_arr)

15. Generated array: [ 52  93  15  72  61  21  83  87  75  75  88 100  24   3  22  53   2  88
  30  38]


In [8]:
# Q16: Find all even numbers
even_nums = rand_arr[rand_arr % 2 == 0]
print("16. Even numbers:", even_nums)

16. Even numbers: [ 52  72  88 100  24  22   2  88  30  38]


In [9]:
# Q17: Replace values below 50 with 0
modified_arr = np.where(rand_arr < 50, 0, rand_arr)
print("17. Replaced values < 50 with 0:", modified_arr)

17. Replaced values < 50 with 0: [ 52  93   0  72  61   0  83  87  75  75  88 100   0   0   0  53   0  88
   0   0]


In [10]:
# Q18: Sort in ascending and descending order
print("18. Ascending:", np.sort(rand_arr))
print("    Descending:", np.sort(rand_arr)[::-1])

18. Ascending: [  2   3  15  21  22  24  30  38  52  53  61  72  75  75  83  87  88  88
  93 100]
    Descending: [100  93  88  88  87  83  75  75  72  61  53  52  38  30  24  22  21  15
   3   2]


In [11]:
# Q19: Find unique values and their frequencies
vals, counts = np.unique(rand_arr, return_counts=True)
print("19. Unique values & frequencies:")
for v, c in zip(vals, counts):
    print(f"    Value {v}: {c} time(s)")

19. Unique values & frequencies:
    Value 2: 1 time(s)
    Value 3: 1 time(s)
    Value 15: 1 time(s)
    Value 21: 1 time(s)
    Value 22: 1 time(s)
    Value 24: 1 time(s)
    Value 30: 1 time(s)
    Value 38: 1 time(s)
    Value 52: 1 time(s)
    Value 53: 1 time(s)
    Value 61: 1 time(s)
    Value 72: 1 time(s)
    Value 75: 2 time(s)
    Value 83: 1 time(s)
    Value 87: 1 time(s)
    Value 88: 2 time(s)
    Value 93: 1 time(s)
    Value 100: 1 time(s)


In [12]:
matrix_5x5 = np.random.rand(5, 5)
print("5x5 Random Matrix:\n", matrix_5x5)
print("\nRow-wise means:", np.mean(matrix_5x5, axis=1))
print("Column-wise means:", np.mean(matrix_5x5, axis=0))

5x5 Random Matrix:
 [[7.78765841e-04 9.92211559e-01 6.17481510e-01 6.11653160e-01
  7.06630522e-03]
 [2.30624250e-02 5.24774660e-01 3.99860972e-01 4.66656632e-02
  9.73755519e-01]
 [2.32771340e-01 9.06064345e-02 6.18386009e-01 3.82461991e-01
  9.83230886e-01]
 [4.66762893e-01 8.59940407e-01 6.80307539e-01 4.50499252e-01
  1.32649612e-02]
 [9.42201756e-01 5.63288218e-01 3.85416503e-01 1.59662522e-02
  2.30893826e-01]]

Row-wise means: [0.44583826 0.39362385 0.46149133 0.49415501 0.42755331]
Column-wise means: [0.33311544 0.60616426 0.54029051 0.30144926 0.4416423 ]


In [13]:
# Formula: (X - min) / (max - min)
arr_norm = np.array([10, 25, 40, 55, 70, 85, 100], dtype=float)
normalized = (arr_norm - np.min(arr_norm)) / (np.max(arr_norm) - np.min(arr_norm))
print("Original Array:", arr_norm)
print("Normalized Array (0 to 1 scale):", normalized)

Original Array: [ 10.  25.  40.  55.  70.  85. 100.]
Normalized Array (0 to 1 scale): [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [14]:
# Formula: (X - mean) / std
arr_std = np.array([150, 160, 165, 170, 175, 180, 190], dtype=float)
standardized = (arr_std - np.mean(arr_std)) / np.std(arr_std)
print("Original Array:", arr_std)
print("Standardized Array (Mean=0, Std=1):", standardized)

Original Array: [150. 160. 165. 170. 175. 180. 190.]
Standardized Array (Mean=0, Std=1): [-1.63299316 -0.81649658 -0.40824829  0.          0.40824829  0.81649658
  1.63299316]


In [15]:
exam_marks = np.random.randint(0, 101, size=100)

range_0_39 = np.sum((exam_marks >= 0) & (exam_marks <= 39))
range_40_59 = np.sum((exam_marks >= 40) & (exam_marks <= 59))
range_60_79 = np.sum((exam_marks >= 60) & (exam_marks <= 79))
range_80_100 = np.sum((exam_marks >= 80) & (exam_marks <= 100))

print("0–39 range count:", range_0_39)
print("40–59 range count:", range_40_59)
print("60–79 range count:", range_60_79)
print("80–100 range count:", range_80_100)

0–39 range count: 40
40–59 range count: 18
60–79 range count: 20
80–100 range count: 22


In [16]:
import time

size = 1_000_000

# Python List Multiplication
py_list = list(range(1, size + 1))
start_time = time.time()
py_result = [x * 2 for x in py_list]
py_time = time.time() - start_time

# NumPy Array Multiplication
np_array = np.arange(1, size + 1)
start_time = time.time()
np_result = np_array * 2
np_time = time.time() - start_time

print(f"Python List Execution Time: {py_time:.6f} seconds")
print(f"NumPy Array Execution Time: {np_time:.6f} seconds")
print(f"NumPy is {py_time / np_time:.2f}x faster!")

Python List Execution Time: 0.037333 seconds
NumPy Array Execution Time: 0.002768 seconds
NumPy is 13.49x faster!
